# Generated by Django 5.1.3 on 2024-11-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog_main",
            name="author",
            field=models.CharField(max_length=200),
        ),
    ]
