# Generated by Django 5.1.3 on 2024-11-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_main_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog_main",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
